# <GfxWindow>:
#     canvas:
#         Rectangle:
#             pos: 5 , 5
#             size: 10, 10
#             group: 'a'
#
#     Label:
#         font_size: 70
#         center_x: root.width / 4
#         top: root.top - 50
#         text: "0"
#         id: l1
#
#     Label:
#         font_size: 70
#         center_x: root.width * 3 / 4
#         top: root.top - 50
#         text: "0"
#         id: l2
